1 Installation et chargement de NumPy

In [11]:
import numpy as np

2 Création des données avec numpy

2.1 Créer un numpy array avec une liste (matrice)

In [14]:
# Création à partir d'une liste
liste = [1, 2, 3, 4, 5] #Définition de la liste d'élément
array_with_list = np.array(liste)
print(array_with_list) #affiche la liste

[1 2 3 4 5]


In [15]:
# Création à partir d'une matrice
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #Définition de la liste de matrice
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.2 Créer un numpy array à partir des fonctions intégrées

In [17]:
#Créer un numpy array à partir de la fonction zéros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#Créer un numpy array à partir de la fonction ones
array_ones = np.ones((3,3))#3 lignes, 3 colonnes
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#Créer un numpy array avec la fonction eye
array_eye = np.eye(2)#Pour créer la matrice identité
array_eye

array([[1., 0.],
       [0., 1.]])

In [20]:
#Créer un numpy array avec la fonction arange: pour créer des nombres entre 
#le minimum et le maximum
array_arange = np.arange(0, 11, 2)
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [21]:
#Créer un numpy array avec la fonction linspace #générer une séquence de nombres
#entre deux valeurs données avec un nombre de points donné
array_linspace = np.linspace(0, 1, 10)#Très utile pour les graphiques
array_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
#Créer un numpy array de valeurs aléatoires avec la fonction random
array_random = np.random.random((4,3))#Très utile pour les graphiques
print(array_random)

[[0.03436449 0.92496195 0.42326683]
 [0.50101746 0.47780323 0.0129114 ]
 [0.90015638 0.126421   0.05366355]
 [0.22410511 0.7792237  0.51751861]]


3 Fonctions mathématiques et statistiques avec Numpy

In [24]:
#fonctions mathématiques basiques
array1=array_with_list
array_sum = np.sum(array1)
aray_mean = np.mean(array1)
array_std = np.std(array1)
array_min = np.min(array1)
array_max = np.max(array1)
array_sqrt = np.sqrt(array1)
array_abs = np.abs(array1)
array_power = np.power(array1, 2)
array_exp = np.exp(array1)
array_log = np.log(np.abs(array1))
array_sin = np.sin(array1)
array_median = np.median(array1)
array_sum

15

In [25]:
array_median

3.0

4 Manipulation des matrices avec Numpy

In [27]:
# Produit matriciel
matrice = [[1, 2, 3], [5, 6, 7], [9, 10, 11]]
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [42]:
# Transposée
transposee = np.transpose(array_with_matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [44]:
# Inversion (pour les matrices carrées non singilières)
inverse = np.linalg.inv(array_eye)
print(inverse)


[[1. 0.]
 [0. 1.]]


In [46]:
# Déterminant
determinant = np.linalg.det(array_eye)
print(determinant)

1.0


5 Accéder aux éléments, sélectionner, modifier et mettre à jour un numpy array

In [51]:
# Accès aux éléments 
array1 = np.array([1,2,3,4,5])
premier_element = array1[0]
print(premier_element)

1


In [53]:
array1[2]

3

In [55]:
# Modification d'un élément
array1[0] = 15
print(array1)

[15  2  3  4  5]


In [57]:
# Séléction des éléments qui respectent une condition
condition = array1 > 5
elements_respectant_condition = array1[array1 > 3]
elements_respectant_condition

array([15,  4,  5])

In [61]:
condition = array1 > 3
condition
indices = np.where(array1 > 3)
indices

(array([0, 3, 4], dtype=int64),)

In [63]:
array1 > 5

array([ True, False, False, False, False])

In [65]:
#Utilisation de np.where
indices = np.where(array1 > 5)
elements_respectant_condition_np_where = array1[indices]
print(elements_respectant_condition_np_where)

[15]


In [67]:
# Mise à jour d'un numpy array
array1[condition] = 0
print(array1)


[0 2 3 0 0]


In [69]:
# Slicing et indexation avancée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :]
premiere_ligne
          

array([1, 2, 3])

In [71]:
#Première colonne
premiere_colonne = array6[:, 0]
premiere_colonne

array([1, 4, 7])

In [73]:
#sous matrice
sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [75]:
# Indexation avancée
lignes = [0, 1]
colonnes = [1, 2]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes


array([2, 6])

In [77]:
#Opérations élémentaires et diffusion (broadcasting)
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])

#Addition élémentaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [79]:
#Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [83]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9 + array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

6 Redimensionnement, append, type de données, taille etc

In [92]:
#redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [94]:
array3 = np.arange(9)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
#Ajouter dres éléments dans un numpy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

[0 2 3 0 0 6 7 8]


In [98]:
#Connaitre les caractéristiques d'un numpy array
array_with_matrice.shape#dimension de l'array

(3, 3)

In [102]:
#Connaitre le type de l'objet
type(array_with_matrice)

numpy.ndarray

In [104]:
#Connaitre les types des éléments
array1.dtype#type des objets

dtype('int32')

In [106]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')